Add missing RISC-V symbols
`sys_linux_riscv64.go` is based on `sys_linux_amd64.go` and `ioctl.h`
from Linux RISC-V.

Fixes error:

  sys_linux.go:8:19: undefined: sysSIOCINQ
  sys_linux.go:9:19: undefined: sysSIOCOUTQ